todo/main/urls.py
from django.urls import path 
from . import views
from .views import TaskCreateView, PersonListView
app_name = "main"
urlpatterns = [
    path('', views.taskList, name="tasks-list"), #name = обратное разрешение интернет-адресов
    path('<int:category_id>/', views.show_category, name="show-category"),
    #Маршруты, содержащие URL-параметры, носят название параметризованных
    path('create', TaskCreateView.as_view(), name="create"),
    path('table', PersonListView.as_view(), name="table"),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model): #Вторичная
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Пользователь")
    title = models.CharField(max_length=200, verbose_name="Что нужно сделать")
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, verbose_name="Оцените задачу по уровню важности")
    #Первым параметром конструктуру этого класса передается строка с именем класса первичной модели, поскольку вторичная модель у нас объявлена раньше первичной
    #все поля модели обязательны к заполнению. следовательно, добавить новое обязателное к заполнению поле в модель, которая уже содержит записи,
    #нельзя — сама СУБД откажется это делать и выведет сообщение об ошибке
    #нам придется пометить поле category как необязательное, присвоим параметру null значение True
    description = models.TextField(null=True, blank=True, verbose_name="Описание")
    complete = models.BooleanField(default=False, verbose_name="Действие завершено?")
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    def __str__(self):
        return self.title 
    class Meta:
        verbose_name_plural = "Задачи" #Название модели во множетсвенном числе
        verbose_name = "Задача" #Название модели в единственном числе
        ordering = ['-created']

class Category(models.Model): #Первичная
    name = models.CharField(max_length=200, db_index=True, verbose_name="Оцените задачу по уровню важности")
    class Meta:
        verbose_name_plural = "Категории"
        verbose_name = "Категория"
        ordering = ["name"]
    def __str__(self):
        return self.name

todo/main/forms.py
from django.forms import ModelForm 
from .models import Task 
class TaskForm(ModelForm):
    class Meta: 
        model = Task 
        fields = ("title", "category", "description", "complete",)

todo/main/views.py
from django.shortcuts import render
from django.http import HttpResponse 
from .models import Task, Category
from django.template import loader 
from django.shortcuts import render 
from django.views.generic.edit import CreateView
from .forms import TaskForm
from django.urls import reverse_lazy
# Create your views here.

from django.views.generic import ListView

class PersonListView(ListView):
    model = Task
    template_name = "main/table.html"



def taskList(request): #taskList - наш контролер / вид / представление 
    """
    s = "Список объявлений \r\n\r\n\r\n"
    for task in Task.objects.order_by('-created'):
        s += task.title + ":" + task.created
    return HttpResponse(s, content_type="text/plain; charset=utf-8")
    
    """
    #любой контролер-функция в качестве единственного обязательного параметра (request) принимает экземпляр класса HttpRequest
    #HttpRequest хранит различные сведения о получаемом запросе: запрашиваемый интернет-адрес, данные, полученные от поситителя и т.д
    """
    template = loader.get_template("main/taskList.html")
    tasks = Task.objects.order_by("-created")
    context = {"tasks":tasks}
    return HttpResponse(template.render(context, request))
    """
    #Выполняем рендеринг шаблона, т.е. генерирование на его основе веб-страницы
    #Использум средства более высокого уровня из моделя shortcuts для выполнения рендеринга шаблона
    tasks = Task.objects.all()
    categories = Category.objects.all()
    return render(request, "main/taskList.html", {"tasks":tasks, "categories":categories})

def show_category(request, category_id):
    tasks = Task.objects.filter(category=category_id)
    categories = Category.objects.all()
    current_category = Category.objects.get(pk=category_id)
    context = {"tasks":tasks, "categories":categories, 
    "current_category":current_category}
    return render(request, 'main/show_category.html', context)

#Класс-контролер
class TaskCreateView(CreateView):
    template_name = 'main/create.html' #Путь к файлу шаблона, создающего страницу с формой
    form_class = TaskForm 
    success_url = reverse_lazy('main:tasks-list') #интернет-адрес для перенаправления после успешного сохранения данных
    #функция reverse_lazy() принимает значение маршрута и значение всех входящих в маршрут URL-параметров
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) #Получаем контекст шаблона от метода базового класса
        context['categories'] = Category.objects.all() #Добавляем в него список категорий
        return context

todo/main/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Главная{% endblock %}:: Доска объявлений</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'main/img/meditation.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">
        {% block extra_head_links %}
        {% endblock %}
    </head>
    <body>
            <nav>
                <ul>
                    <li><a href="{% url 'main:tasks-list' %}">Главная</a></li>
                    <li><a href="{% url 'main:create' %}">Добавить запись</a></li>
                    {% for category in categories %}
                        <li><a href="{% url 'main:show-category' category.pk %}">{{ category.name }}</a></li>
                    {% endfor %}
                <ul>
            </nav>
            <div class="container">
            {% block content %}   
            {% endblock %}  
            </div>
    </body>
</html>

todo/main/templates/main/create.html
{% extends "layout/base.html" %}
{% load static %}
{% block title %}Добавление новых задач{% endblock %}
{% block content %}
        <form method=POST>
        <!--Мы указали метод отправки POST, но не записали интернет-адрес по которому будут отправлены данные из формы.
        В этом случае данные будут отправлены по тому же адресу, с которого была загружена страница, т.е в нашем случае 
        тому же контролер-классу TaskCreateView, который благополучно обработает и сохранит их-->
            {% csrf_token %}
            <!--в теге <form> мы поместили тег шаблонизатора csrf token. Он создает в форме 
                скрытое поле, хранящее цифровой жетон, получив который контроллер ’’пой­
                мет”, что данные были отправлены с текущего сайта и им можно доверять. Это 
                часть подсистемы безопасности Django.-->
            {{ form.as_p }}
            <!--для вывода формы, элементы управления которой находятся на отдельных абза­цах,
            применяется метод as p () класса формы;-->
            <input type="submit" value="Добавить">
        </form>
{% endblock %}

todo/main/templates/main/show_category.html
{% extends "layout/base.html" %}
{% load static %}
{% block title %}Категории{% endblock %}
{% block content %}
        {% for task in tasks %}
            <div>
                <h3>{{ task.title|truncatewords:5 }}</h3>
                <p>{{ task.description|linebreaks }}</p>
                <p>{{ task.created|date:"d.m.Y H:i:s" }}</p>
                <hr>
            </div>
        {% endfor %}
{% endblock %}

todo/main/templates/main/table.html
{% extends "layout/base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load i18n %}
{% load bootstrap3 %}
<!doctype html> 
<html>
    <head> 
        <title>List of persons</title> 
    </head> 
    <body> 
        {% render_table object_list %} 
    </body> 
</html>

todo/main/templates/main/taskList.html
{% extends "layout/base.html" %}
{% load static %}
{% block extra_head_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/taskList.css' %}">
{% endblock %}
{% block content %}
    <h1>Планы:</h1>
    {% for task in tasks %}
        <div class="main"> 
            <h3>{{ task.title|truncatewords:5|upper }}</h3>
            <div class="list">
                <p>{{ task.description|linebreaks }}</p>
                <p>{{ task.category.name }}</p>
                <p>{{ task.created|date:"d.m.Y H:i:s" }}</p>
            </div class="main">
        </div> 
    {% endfor %}
{% endblock %}
    